### ISSUE TITLE
Https Login

### ISSUE THREAD

**Issue by NicoHood** [volumio/Volumio2#1166]
It would be nice to have the web frontend available with https. This way all data is encrypted, especially the login, for example if you configure spotify. A self signed https cert would be okay. You can trust it and then the traffic is encrypted.

**Comment by volumio** [comment]
That makes no sense, sorry. There is no way we can have https on local volumio, for various reasons, the first of which is, if self singned you will get a ton of warnings by every browser

**Comment by koenbuyens** [comment]
It would be great if 
- all the references to http:// in the code-base are replaced with protocol-relative URs (i.e. URIs starting with // instead of http:// ). 
- replacing explicit references to the IP address with the hostname of the URI
This would enable me to use nginx as reverse-proxy.

![image](https://user-images.githubusercontent.com/17049884/57990199-53a9ad00-7a72-11e9-97ec-11a457b9182b.png)

**Comment by volumio** [comment]
Https over local network is not possible.

**Comment by koenbuyens** [comment]
I am running https on my local network.

Koen
