### ISSUE TITLE
no NFS system with the Beta 1

### ISSUE THREAD

**Issue by akhlan** [volumio/Volumio2#225]
Hy,

NFS has disappeared with the Beta 1, why?

Rgds
Akhlan

**Comment by volumio** [comment]
It has not disappeared, is just under advanced

**Comment by balbuze** [comment]
I think that this line (nfs, cifs) shouldn't be in advanced...

**Comment by akhlan** [comment]
No, before we have both and now juste cifs...

**Comment by balbuze** [comment]
Are you sure that it is not because it's written in black over grey (very bad contrast) ?
![cifs](https://cloud.githubusercontent.com/assets/12850139/13028172/32065cae-d267-11e5-8380-dd73dfac6d4d.png)
![nfs](https://cloud.githubusercontent.com/assets/12850139/13028177/48f79856-d267-11e5-8ed0-fb9f78ea0147.png)

**Comment by akhlan** [comment]
oupsssssssssss, tks balbuze ;)
