### ISSUE TITLE
[beta4] Encoding issue on Playback View

### ISSUE THREAD

**Issue by dragotin** [volumio/Volumio2#285]
German umlauts are not properly decoded on the Playback page:
![screenshot_20160318_165406](https://cloud.githubusercontent.com/assets/1070214/13883560/45563b34-ed2a-11e5-8a9f-133d7f795c08.png)

The file comes from a mounted smb storage. In the Browse view, it says properly *Panik Präsident* as it should be so I assume the encoding of the filename is fine.

**Comment by balbuze** [comment]
have a look to check tag of the track. I had such problem, and I found it was the tag that contain such problem (filename was ok)

**Comment by dragotin** [comment]
Hmm, yes, good point. I am not sure how I can find out the encoding of the tags tough.

mp3info shows this:
```
File: 02-Cello.mp3
Title:   Cello                          Track: 2
Artist:  Udo Lindenberg
Album:   Panik Präsident               Year:  2003
```
which looks ok.

**Comment by apinner** [comment]
@dragotin did you figure out this issue?

**Comment by dragotin** [comment]
No, actually I think the mp3 file tags are fine and would suspect  a bug in the view.

**Comment by apinner** [comment]
@dragotin I created a couple of mp3 files, one with the same name and tags as yours, and another that was just pure umlauts. They display absolutely fine for me, I think the issue is probably with your tags.

![udo](https://cloud.githubusercontent.com/assets/85802/14242084/4cb0a106-fa47-11e5-8d88-83dc459870fd.PNG)

![umlauts](https://cloud.githubusercontent.com/assets/85802/14242087/51590c48-fa47-11e5-8585-d4baf907ac0f.PNG)

**Comment by dragotin** [comment]
All right. Let's close this for now, thanks for investigation.
