### ISSUE TITLE
Volumio RC2/ Odroid C2: Choosing the NAS from the browse feature (latest version directly built from repo)

### ISSUE THREAD

**Issue by gkkpch** [volumio/Volumio2#627]
Noticed a problem with adding new music the My Music, the latest version seems to have a problem with selecting music libraries from detected NAS devices. It fills/displays the alias as the name of the selected music directory, as NAS IP address it takes the alias of the NAS device and path is correctly shown as the name of the selected music directory. As this is saved as config parameters it might explain why people have problems when connecting to their NAS after rebooting. 

When I enter all values manually, it seems to work ok.

**Comment by xipmix** [comment]
I took a look at this. The story starts in the Volumio2-UI code, where src/app/plugin/core-plugin/network-drives-plugin.controller.js does this when you pick a share from the detected list:
```
selectShare(share, disk) {
    this.drive.ip = share.name;
    this.drive.name = disk.sharename;
    this.drive.path = disk.path;
}
```
The input to this comes from discoverShares which calls ```smbtree``` to do the discovery and uses the results to create a json data structure, eg:
```
{ nas:
  [  { name: "littlebox", shares: [ { sharename:"A share", path:"A share" } ] },
     { name: "bigbox", shares: [ { sharename:"share1", path:"share1" },
                                               { sharename:"share2", path:"share2" }
                                             ]
     }
  ]
}
```
Let's relate that to your observations, assuming you pick ```\\littlebox\A share```:
 * fills the alias as the name of the selected music directory.
   So you should get 'A share'. That's how it works for me (2.041).

 * as NAS IP address it takes the alias of the NAS device.
   You should get 'littlebox' here. This is the netbios name the NAS sends out in response to browse queries. To connect up the share, volumio uses ```mount.cifs``` and _if netbios name resolution is working_, the mount does actually happen. It might be more robust to have discoverShares do an nmblookup and if it works, add the returned IP address to the data structure. Because IP addresses might change over time (dhcp pools), the name resolution would have to be checked before every mount attempt.

 * path is correctly shown as the name of the selected music directory.
   As you note 'sharename' and 'path' are the same thing. This is deliberate; discoverShares puts the exact same string in both elements of the structure.

So I think the behaviour you describe is what is intended. Why are there problems with reconnecting ? Probably related to the samba config in volumio, but also likely to depend on what's going on in the network around it. If you can recall specific cases it might help move things along.

Question: when you enter all values manually, I assume you use an IP address in the IP address field, not a netbios name?
