### ISSUE TITLE
Web interface not updating

### ISSUE THREAD

**Issue by jbmfg** [volumio/Volumio2#947]
I leave volumio open in a tab that is no in focus most of the time.  SInce the latest update when i go back to that tab the currently playing song is not displayed.  The music is playing fine but the album art is for an earlier song.  If i refresh the whole page it displays as expected

**Comment by Nicolas-94** [comment]
Hello 
Same thing on my side. all details on https://github.com/volumio/Volumio2-UI/issues/242
this issue 242 was closed, however, the issue is still present (even if not systematic), with Volumio 2.041
@volumio, 
As this issue #947 is still opened, let's follow it here ;)
if you need more logs  just tell me. 

Nicolas
